name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: Install dependencies
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      
      - name: Tests
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
      
      - name: Build
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
