name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm run install
      
      - name: Tests
        run: npm run test
      
      - name: Build
        run: npm run build
          
