name: Vercel Dev Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORGID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECTID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          submodules: recursive

      - name: Copy .env
        run: echo "${{ secrets.DOTENV }}" | base64 -d > .env

      - name: Install Vercel CLI
        run: npm i -g vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_SECRETKEY }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_SECRETKEY }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_SECRETKEY }}
