name: Vercel Dev Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORGID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECTID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          submodules: recursive

      - name: Use pnpm
        run: corepack enable && pnpm i vercel@canary

      - name: Pull Vercel Environment Information
        run: pnpm exec vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_SECRETKEY }}

      - name: Build Project Artifacts
        run: pnpm exec vercel build --token=${{ secrets.VERCEL_SECRETKEY }}

      - name: Deploy Project Artifacts to Vercel
        run: pnpm exec vercel deploy --prebuilt --token=${{ secrets.VERCEL_SECRETKEY }}
