name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORGID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECTID }}
on:
  push:
    branches:
      - release
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_SECRETKEY }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_SECRETKEY }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_SECRETKEY }}
